### ISSUE TITLE
Moving the drop down menu to the center

### ISSUE THREAD

**Issue by Manjula85** [Manjula85/Project-3#1]
It doesn't let me do it unless I use something like padding or margin-left. But that would change according the window and will not be set at true center unless it's specified as such. Any thoughts?

**Comment by dnguneratne** [comment]
I guess there's 2 ways to do this.

1. Not a good solution. ul needs a predefined width. Not a good responsive design.

```html
<div style="background-color:black">
  <ul style="width:500px;margin:auto">
    <li>The book series</li>
    <li>Testimonials</li>
    <li>The Author</li>
    <li>Free resources</li>
  </ul>
</div>
```

2. Use flexbox. This is the right approach. Responsive too.
```html
<div style="background-color:black;display:flex;justify-content:center">
  <ul>
    <li>The book series</li>
    <li>Testimonials</li>
    <li>The Author</li>
    <li>Free resources</li>
  </ul>
</div>
```

**Comment by Manjula85** [comment]
> I guess there's 2 ways to do this.
> 
> 1. Not a good solution. ul needs a predefined width. Not a good responsive design.
> 
> ```
> <div style="background-color:black">
>   <ul style="width:500px;margin:auto">
>     <li>The book series</li>
>     <li>Testimonials</li>
>     <li>The Author</li>
>     <li>Free resources</li>
>   </ul>
> </div>
> ```
> 
> 1. Use flexbox. This is the right approach. Responsive too.
> 
> ```
> <div style="background-color:black;display:flex;justify-content:center">
>   <ul>
>     <li>The book series</li>
>     <li>Testimonials</li>
>     <li>The Author</li>
>     <li>Free resources</li>
>   </ul>
> </div>
> ```

Yeah this is a much better approach. Thank you.
